### ISSUE TITLE
plugin-filtered-relationship docs + potentially invalid expected model structure

### ISSUE THREAD

**Issue by Aralun** [ForestAdmin/forestadmin-experimental#93]
The readme has a typo:
https://github.com/ForestAdmin/forestadmin-experimental/blob/8d627aab4f7ff94586402b74d7eba11a26f2bb27/packages/plugin-filtered-relationship/README.md#L14

`DefineEnumOptions` should probably be `filteredOneToManyOptions`.

https://github.com/ForestAdmin/forestadmin-experimental/blob/8d627aab4f7ff94586402b74d7eba11a26f2bb27/packages/plugin-filtered-relationship/src/index.ts#L28

I suspect this breaks on my models because I actually have an uppercase `Id`.
I'm getting `ValidationError: Column not found: 'MyCollection.id'`
Maybe this should be `foreignPk`?

If it's not and the issue is a pain to fix, I can always add one more field `id` mapped to my `Id` column in the Sequelize models.

**Comment by DayTF** [comment]
You're right, I fixed both issues, just waiting on npm to update the latest packages.
