### ISSUE TITLE
filtered-relationship ID column type

### ISSUE THREAD

**Issue by Aralun** [ForestAdmin/forestadmin-experimental#95]
I'm getting the following error: `Error: Types from 'MyCollection.MyFilteredRelationshipId' and 'User.Id' do not match.`
I am indeed using string UUIDs.

This may need to be a plugin option to specify the type of the PK? Unless it can be inferred within the plugin itself?

Offending lines:
https://github.com/ForestAdmin/forestadmin-experimental/blob/bec7f441bc9c34e23e31174f36e44f4394df9e88/packages/plugin-filtered-relationship/src/index.ts#L26-L29

(Should have seen it in the previous issue, sorry about that)

**Comment by DayTF** [comment]
No worries, we're finding every stress point thanks to you :D  
The plugin can infer the type, I've prepared the PR just waiting for a review from one of my colleagues https://github.com/ForestAdmin/forestadmin-experimental/pull/96

**Comment by DayTF** [comment]
@Aralun it should be live right now, does it solve your issue ?
